baseURL = 'kritrim.xyz'
languageCode = 'en-us'
title = '/home/kritrim'
theme = 'PaperMod'

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 30

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 40

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  ShowShareButtons = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Welcome to my artificial brain dump! This is where I jot down my thoughts, share my explorations, and document my tech escapades. Sometimes I build cool stuff and troubleshoot technical nightmares, I've got it all documented here. Feel free to look around&mdash; find all posts in the [Archives](/archives/) or delve into specific topics through [Categories](/categories/) or [Tags](/tags/). I hope you can find something useful."
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]