baseURL = 'kritrim.xyz'
languageCode = 'en-us'
title = '/home/ kritrim'
theme = 'PaperMod'

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 30

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 40

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  ShowShareButtons = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]